// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Y6mho6wfdcu1aqfbCzfBA-ZtYqvSPKE',
    appId: '1:879932177448:web:7e55895af101d59d37891d',
    messagingSenderId: '879932177448',
    projectId: 'nike-59377',
    authDomain: 'nike-59377.firebaseapp.com',
    storageBucket: 'nike-59377.firebasestorage.app',
    measurementId: 'G-RQNMLJFR6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK-7FbYW0EusrAtIaRJv5NKZMu91nsuuI',
    appId: '1:879932177448:android:0f585a7057f4dd7f37891d',
    messagingSenderId: '879932177448',
    projectId: 'nike-59377',
    storageBucket: 'nike-59377.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzaEBMKn8JWaGUSaA1bqFLFyhIqB-gszs',
    appId: '1:879932177448:ios:b0f2245157e9867537891d',
    messagingSenderId: '879932177448',
    projectId: 'nike-59377',
    storageBucket: 'nike-59377.firebasestorage.app',
    iosBundleId: 'com.example.nike',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzaEBMKn8JWaGUSaA1bqFLFyhIqB-gszs',
    appId: '1:879932177448:ios:b0f2245157e9867537891d',
    messagingSenderId: '879932177448',
    projectId: 'nike-59377',
    storageBucket: 'nike-59377.firebasestorage.app',
    iosBundleId: 'com.example.nike',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5Y6mho6wfdcu1aqfbCzfBA-ZtYqvSPKE',
    appId: '1:879932177448:web:a66ce71532d4aeae37891d',
    messagingSenderId: '879932177448',
    projectId: 'nike-59377',
    authDomain: 'nike-59377.firebaseapp.com',
    storageBucket: 'nike-59377.firebasestorage.app',
    measurementId: 'G-C5MGEVTQCJ',
  );
}
